#!/bin/bash

# Check that two arguments were provided
if [ $# -ne 2 ]; then
    echo "Usage: $0 <source_directory> <destination_directory>"
    exit 1
fi

SOURCE=$1
DESTINATION=$2

# Run rsync backup
rsync -av --exclude="*.log" --delete "$SOURCE" "$DESTINATION"

# End
